from __future__ import annotations
from app.application.ticket_service import TicketService
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from app.application.automation_service import (
    AutomationService,
)
from app.application.knowledge.retrieval_service import (
    KnowledgeRetrievalService,
)
from app.application.ports.audit_repository import (
    AuditRepository,
)
from app.application.ports.itsm_client import (
    ITSMClient,
)
from app.application.ports.automation_tool import (
    AutomationTool,
)
from app.domain.audit import AuditEvent
from app.domain.enums import (
    AutomationStatus,
    ConsentSource,
    PolicyDecision,
    TicketStatus,
    TicketType,
)
from app.domain.intent import AIIntentAnalysis
from app.domain.ticket import Ticket


@dataclass(frozen=True)
class AutomationResolution:
    """
    Deterministic resolution of an automation candidate.

    This is deliberately NOT generated by the LLM.

    The AI can identify an automation candidate, but the application
    resolves it against an allowlist.
    """

    action: str
    tool: str
    policy_id: str


@dataclass(frozen=True)
class SelfHealingResult:
    """
    Complete result of one self-healing attempt.
    """

    status: str
    message: str

    action_id: str | None = None
    action: str | None = None
    tool: str | None = None

    diagnosis: str | None = None

    knowledge_sources: list[dict[str, Any]] | None = None

    automation_status: AutomationStatus | None = None

    validation_checks: list[str] | None = None

    ticket_id: str | None = None
    external_ticket_id: str | None = None
    external_ticket_number: str | None = None

    audit_event_ids: list[str] | None = None


class SelfHealingWorkflowService:
    """
    Controlled self-healing workflow.

    Flow:

        Employee Request
             ↓
        AI Intent Analysis
             ↓
        Diagnosis
             ↓
        Knowledge Retrieval
             ↓
        Allowlisted Action Resolution
             ↓
        Policy
             ↓
        Consent
             ↓
        Tool Execution
             ↓
        Validation
             ↓
        ITSM Update
             ↓
        Audit

    IMPORTANT:

    The LLM never selects an executable Python function.

    The LLM produces structured intent.

    This service maps that intent to an allowlisted action using
    deterministic application rules.
    """

    PASSWORD_RESET_SUBCATEGORY = "password"

    PASSWORD_RESET_ACTION = "password_reset"

    PASSWORD_RESET_TOOL = "password_reset"

    PASSWORD_RESET_POLICY = "password-reset-v1"

    def __init__(
        self,
        *,
        automation_service: AutomationService,
        knowledge_retrieval_service: KnowledgeRetrievalService,
        audit_repository: AuditRepository,
        ticket_service: TicketService,
        itsm_client: ITSMClient,
        password_reset_tool: AutomationTool,
        knowledge_score_threshold: float = 0.40,
    ) -> None:
        if knowledge_score_threshold < 0:
            raise ValueError(
                "Knowledge score threshold cannot be negative."
            )

        self._automation_service = (
            automation_service
        )

        self._knowledge_retrieval_service = (
            knowledge_retrieval_service
        )

        self._audit_repository = (
            audit_repository
        )

        self._itsm_client = itsm_client

        self._password_reset_tool = (
            password_reset_tool
        )

        self._knowledge_score_threshold = (
            knowledge_score_threshold
        )

    # ------------------------------------------------------------------
    # Public workflow
    # ------------------------------------------------------------------

    def handle(
        self,
        *,
        employee_request: str,
        user_id: str,
        analysis: AIIntentAnalysis,
        consent_granted: bool,
        consent_source: ConsentSource,
        ticket: Ticket | None = None,
    ) -> SelfHealingResult:
        """
        Execute one controlled self-healing workflow.
        """

        employee_request = (
            employee_request.strip()
        )

        user_id = user_id.strip()

        if not employee_request:
            raise ValueError(
                "Employee request cannot be empty."
            )

        if not user_id:
            raise ValueError(
                "User ID cannot be empty."
            )

        audit_event_ids: list[str] = []

        self._record_audit(
            audit_event_ids=audit_event_ids,
            event_type="self_healing_started",
            user_id=user_id,
            ticket_id=(
                ticket.ticket_id
                if ticket is not None
                else None
            ),
            description=(
                "Self-healing workflow started."
            ),
            metadata={
                "request": employee_request,
                "intent": analysis.intent.value,
                "confidence": (
                    analysis.confidence.value
                ),
            },
        )

        # --------------------------------------------------------------
        # 1. Safety gate
        # --------------------------------------------------------------

        if not analysis.automation_candidate:
            self._record_audit(
                audit_event_ids=audit_event_ids,
                event_type="self_healing_rejected",
                user_id=user_id,
                ticket_id=(
                    ticket.ticket_id
                    if ticket is not None
                    else None
                ),
                description=(
                    "AI analysis did not mark the request as "
                    "an automation candidate."
                ),
                metadata={},
            )

            return SelfHealingResult(
                status="not_automatable",
                message=(
                    "The request was not identified as a "
                    "safe automation candidate."
                ),
                audit_event_ids=audit_event_ids,
            )

        # --------------------------------------------------------------
        # 2. Diagnose
        # --------------------------------------------------------------

        diagnosis = self._diagnose(
            analysis
        )

        self._record_audit(
            audit_event_ids=audit_event_ids,
            event_type="self_healing_diagnosed",
            user_id=user_id,
            ticket_id=(
                ticket.ticket_id
                if ticket is not None
                else None
            ),
            description=diagnosis,
            metadata={
                "category": (
                    analysis.category or ""
                ),
                "subcategory": (
                    analysis.subcategory or ""
                ),
            },
        )

        if diagnosis is None:
            return SelfHealingResult(
                status="escalation_required",
                message=(
                    "The issue could not be diagnosed "
                    "as a supported self-healing scenario."
                ),
                audit_event_ids=audit_event_ids,
            )

        # --------------------------------------------------------------
        # 3. Knowledge retrieval
        # --------------------------------------------------------------

        knowledge_sources = (
            self._retrieve_knowledge(
                employee_request
            )
        )

        self._record_audit(
            audit_event_ids=audit_event_ids,
            event_type="self_healing_knowledge_retrieved",
            user_id=user_id,
            ticket_id=(
                ticket.ticket_id
                if ticket is not None
                else None
            ),
            description=(
                "Approved knowledge retrieved for "
                "self-healing diagnosis."
            ),
            metadata={
                "source_count": str(
                    len(knowledge_sources)
                ),
            },
        )

        if not knowledge_sources:
            self._record_audit(
                audit_event_ids=audit_event_ids,
                event_type="self_healing_escalated",
                user_id=user_id,
                ticket_id=(
                    ticket.ticket_id
                    if ticket is not None
                    else None
                ),
                description=(
                    "Self-healing stopped because "
                    "approved knowledge was insufficient."
                ),
                metadata={},
            )

            return SelfHealingResult(
                status="escalation_required",
                message=(
                    "I could not find sufficiently relevant "
                    "approved knowledge to safely automate "
                    "this request."
                ),
                diagnosis=diagnosis,
                knowledge_sources=knowledge_sources,
                audit_event_ids=audit_event_ids,
            )

        # --------------------------------------------------------------
        # 4. Deterministic action resolution
        # --------------------------------------------------------------

        resolution = self._resolve_action(
            analysis
        )

        if resolution is None:
            self._record_audit(
                audit_event_ids=audit_event_ids,
                event_type="self_healing_escalated",
                user_id=user_id,
                ticket_id=(
                    ticket.ticket_id
                    if ticket is not None
                    else None
                ),
                description=(
                    "No allowlisted automation action "
                    "matched the diagnosis."
                ),
                metadata={},
            )

            return SelfHealingResult(
                status="escalation_required",
                message=(
                    "The issue may be automatable, but "
                    "no approved automation action exists "
                    "for this diagnosis."
                ),
                diagnosis=diagnosis,
                knowledge_sources=knowledge_sources,
                audit_event_ids=audit_event_ids,
            )

        self._record_audit(
            audit_event_ids=audit_event_ids,
            event_type="self_healing_action_resolved",
            user_id=user_id,
            ticket_id=(
                ticket.ticket_id
                if ticket is not None
                else None
            ),
            description=(
                "A deterministic allowlisted automation "
                "action was selected."
            ),
            metadata={
                "action": resolution.action,
                "tool": resolution.tool,
                "policy_id": resolution.policy_id,
            },
        )

        # --------------------------------------------------------------
        # 5. Create controlled automation action
        # --------------------------------------------------------------

        action = (
            self._automation_service.create_action(
                user_id=user_id,
                action=resolution.action,
                tool=resolution.tool,
                policy_id=resolution.policy_id,
                policy_decision=(
                    PolicyDecision.ALLOWED
                ),
                consent_granted=consent_granted,
                consent_source=consent_source,
                ticket_id=(
                    ticket.ticket_id
                    if ticket is not None
                    else None
                ),
            )
        )

        self._record_audit(
            audit_event_ids=audit_event_ids,
            event_type="automation_policy_evaluated",
            user_id=user_id,
            ticket_id=(
                ticket.ticket_id
                if ticket is not None
                else None
            ),
            action_id=action.action_id,
            description=(
                "Automation policy evaluated."
            ),
            metadata={
                "policy_id": resolution.policy_id,
                "decision": (
                    action.policy.decision.value
                ),
                "consent_granted": str(
                    consent_granted
                ),
            },
        )

        # --------------------------------------------------------------
        # 6. Authorization
        # --------------------------------------------------------------

        action = (
            self._automation_service.authorize(
                action
            )
        )

        if action.status != AutomationStatus.AUTHORIZED:
            self._record_audit(
                audit_event_ids=audit_event_ids,
                event_type="automation_not_authorized",
                user_id=user_id,
                ticket_id=(
                    ticket.ticket_id
                    if ticket is not None
                    else None
                ),
                action_id=action.action_id,
                description=(
                    "Automation was not authorized."
                ),
                metadata={
                    "status": action.status.value,
                    "policy_decision": (
                        action.policy.decision.value
                    ),
                    "consent_granted": str(
                        action.consent.granted
                    ),
                },
            )

            return SelfHealingResult(
                status=(
                    "confirmation_required"
                    if not consent_granted
                    else "automation_denied"
                ),
                message=(
                    "The automation cannot proceed "
                    "without the required authorization."
                ),
                action_id=action.action_id,
                action=action.action,
                tool=action.tool,
                diagnosis=diagnosis,
                knowledge_sources=knowledge_sources,
                automation_status=action.status,
                audit_event_ids=audit_event_ids,
            )

        # --------------------------------------------------------------
        # 7. Execute
        # --------------------------------------------------------------

        action = (
            self._automation_service.execute(
                action
            )
        )

        self._record_audit(
            audit_event_ids=audit_event_ids,
            event_type="automation_execution_started",
            user_id=user_id,
            ticket_id=(
                ticket.ticket_id
                if ticket is not None
                else None
            ),
            action_id=action.action_id,
            description=(
                "Approved automation execution started."
            ),
            metadata={
                "tool": action.tool,
            },
        )

        try:
            execution_result = (
                self._password_reset_tool.execute(
                    user_id=user_id
                )
            )

            validation_checks = (
                self._password_reset_tool.validate(
                    user_id=user_id
                )
            )

        except Exception as exc:
            action = self._automation_service.fail(
                action,
                error=str(exc),
            )

            self._record_audit(
                audit_event_ids=audit_event_ids,
                event_type="automation_failed",
                user_id=user_id,
                ticket_id=(
                    ticket.ticket_id
                    if ticket is not None
                    else None
                ),
                action_id=action.action_id,
                description=(
                    "Automation execution failed."
                ),
                metadata={
                    "error": str(exc),
                },
            )

            incident = self._create_failure_incident(
                user_id=user_id,
                action=action,
                original_request=employee_request,
            )

            if incident is not None:
                self._record_audit(
                    audit_event_ids=audit_event_ids,
                    event_type="self_healing_escalated",
                    user_id=user_id,
                    ticket_id=incident.ticket_id,
                    action_id=action.action_id,
                    description=(
                        "Automation failed and the issue "
                        "was escalated to an incident."
                    ),
                    metadata={},
                )

            return SelfHealingResult(
                status="automation_failed",
                message=(
                    "The automated remediation failed. "
                    "The issue has been escalated."
                ),
                action_id=action.action_id,
                action=action.action,
                tool=action.tool,
                diagnosis=diagnosis,
                knowledge_sources=knowledge_sources,
                automation_status=action.status,
                ticket_id=(
                    incident.ticket_id
                    if incident is not None
                    else None
                ),
                audit_event_ids=audit_event_ids,
            )

        # --------------------------------------------------------------
        # 8. Complete + validate
        # --------------------------------------------------------------

        action = self._automation_service.complete(
            action,
            result=execution_result,
            validation_checks=validation_checks,
        )

        self._record_audit(
            audit_event_ids=audit_event_ids,
            event_type="automation_validated",
            user_id=user_id,
            ticket_id=(
                ticket.ticket_id
                if ticket is not None
                else None
            ),
            action_id=action.action_id,
            description=(
                "Automation completed and validation "
                "checks passed."
            ),
            metadata={
                "validation_count": str(
                    len(validation_checks)
                ),
            },
        )

        # --------------------------------------------------------------
        # 9. Update ITSM
        # --------------------------------------------------------------

        external_ticket_id = None
        external_ticket_number = None

        if ticket is not None:
            external_ticket_id = (
                ticket.external_ticket_id
            )

            external_ticket_number = (
                ticket.external_ticket_number
            )

            if external_ticket_id:
                try:
                    self._itsm_client.update_ticket(
                        external_ticket_id,
                        status=TicketStatus.RESOLVED,
                        description=(
                            "Self-healing completed successfully. "
                            "Password reset was executed and validated."
                        ),
                    )

                    self._record_audit(
                        audit_event_ids=audit_event_ids,
                        event_type="itsm_updated",
                        user_id=user_id,
                        ticket_id=ticket.ticket_id,
                        action_id=action.action_id,
                        description=(
                            "External ITSM record updated "
                            "after successful self-healing."
                        ),
                        metadata={
                            "external_ticket_id": (
                                external_ticket_id
                            ),
                            "status": (
                                TicketStatus.RESOLVED.value
                            ),
                        },
                    )

                except Exception as exc:
                    self._record_audit(
                        audit_event_ids=audit_event_ids,
                        event_type="itsm_update_failed",
                        user_id=user_id,
                        ticket_id=ticket.ticket_id,
                        action_id=action.action_id,
                        description=(
                            "Self-healing succeeded, but the "
                            "external ITSM update failed."
                        ),
                        metadata={
                            "error": str(exc),
                        },
                    )

                    return SelfHealingResult(
                        status="completed_itsm_update_failed",
                        message=(
                            "The issue was successfully remediated "
                            "and validated, but the ITSM status could "
                            "not be updated automatically."
                        ),
                        action_id=action.action_id,
                        action=action.action,
                        tool=action.tool,
                        diagnosis=diagnosis,
                        knowledge_sources=knowledge_sources,
                        automation_status=action.status,
                        validation_checks=validation_checks,
                        ticket_id=ticket.ticket_id,
                        external_ticket_id=(
                            external_ticket_id
                        ),
                        external_ticket_number=(
                            external_ticket_number
                        ),
                        audit_event_ids=audit_event_ids,
                    )

        self._record_audit(
            audit_event_ids=audit_event_ids,
            event_type="self_healing_completed",
            user_id=user_id,
            ticket_id=(
                ticket.ticket_id
                if ticket is not None
                else None
            ),
            action_id=action.action_id,
            description=(
                "Self-healing completed successfully."
            ),
            metadata={
                "result": action.result or "",
            },
        )

        return SelfHealingResult(
            status="resolved",
            message=(
                "Your password issue was automatically "
                "resolved and validated."
            ),
            action_id=action.action_id,
            action=action.action,
            tool=action.tool,
            diagnosis=diagnosis,
            knowledge_sources=knowledge_sources,
            automation_status=action.status,
            validation_checks=validation_checks,
            ticket_id=(
                ticket.ticket_id
                if ticket is not None
                else None
            ),
            external_ticket_id=(
                external_ticket_id
            ),
            external_ticket_number=(
                external_ticket_number
            ),
            audit_event_ids=audit_event_ids,
        )

    # ------------------------------------------------------------------
    # Diagnosis
    # ------------------------------------------------------------------

    @classmethod
    def _diagnose(
        cls,
        analysis: AIIntentAnalysis,
    ) -> str | None:
        """
        Convert validated AI classification into a controlled
        diagnosis.

        This is deliberately deterministic.
        """

        if not analysis.automation_candidate:
            return None

        category = (
            analysis.category or ""
        ).strip().lower()

        subcategory = (
            analysis.subcategory or ""
        ).strip().lower()

        summary = (
            analysis.summary or ""
        ).strip().lower()

        password_terms = (
            "password",
            "expired",
            "password expired",
            "credential expired",
        )

        if (
            "identity" in category
            or "account" in category
            or "password" in category
            or "password" in subcategory
            or any(
                term in summary
                for term in password_terms
            )
        ):
            return (
                "Password expiry / password reset "
                "scenario."
            )

        return None

    # ------------------------------------------------------------------
    # Knowledge
    # ------------------------------------------------------------------

    def _retrieve_knowledge(
        self,
        employee_request: str,
    ) -> list[dict[str, Any]]:
        results = (
            self._knowledge_retrieval_service.hybrid_search(
                employee_request,
                limit=5,
            )
        )

        sources: list[dict[str, Any]] = []

        for result in results:
            score = getattr(
                result,
                "hybrid_score",
                getattr(result, "score", 0.0),
            )

            if score < self._knowledge_score_threshold:
                continue

            sources.append(
                {
                    "document_id": str(
                        result.chunk.document_id
                    ),
                    "chunk_id": str(
                        result.chunk.id
                    ),
                    "title": (
                        result.chunk.metadata.title
                    ),
                    "category": (
                        result.chunk.metadata.category
                    ),
                    "subcategory": (
                        result.chunk.metadata.subcategory
                    ),
                    "score": float(score),
                    "retrieval_method": getattr(
                        result,
                        "retrieval_method",
                        "hybrid",
                    ),
                }
            )

        return sources

    # ------------------------------------------------------------------
    # Deterministic action resolution
    # ------------------------------------------------------------------

    @classmethod
    def _resolve_action(
        cls,
        analysis: AIIntentAnalysis,
    ) -> AutomationResolution | None:
        diagnosis = cls._diagnose(
            analysis
        )

        if diagnosis is None:
            return None

        return AutomationResolution(
            action=cls.PASSWORD_RESET_ACTION,
            tool=cls.PASSWORD_RESET_TOOL,
            policy_id=cls.PASSWORD_RESET_POLICY,
        )

    # ------------------------------------------------------------------
    # Failure escalation
    # ------------------------------------------------------------------

    def _create_failure_incident(
        self,
        *,
        user_id: str,
        action,
        original_request: str,
    ) -> Ticket | None:
        try:
            return self._create_incident_without_external_sync(
                user_id=user_id,
                action=action,
                original_request=original_request,
            )
        except Exception:
            return None

    def _create_incident_without_external_sync(
        self,
        *,
        user_id: str,
        action,
        original_request: str,
    ) -> Ticket:
        """
        This method is intentionally kept small.

        TicketService remains the normal ticket creation boundary.

        If the existing TicketService is configured with the ITSM
        adapter, its normal creation flow can be used by the caller
        instead.

        This helper exists only as a safe fallback for the self-healing
        failure path.
        """

        return self._ticket_service.create_ticket(
            ticket_type=TicketType.INCIDENT,
            title=(
                f"Self-healing failed: {action.action}"
            ),
            description=(
                f"Original request: {original_request}\n"
                f"Automation error: "
                f"{action.execution.error}"
            ),
            user_id=user_id,
        )

    # ------------------------------------------------------------------
    # Audit
    # ------------------------------------------------------------------

    def _record_audit(
        self,
        *,
        audit_event_ids: list[str],
        event_type: str,
        user_id: str,
        description: str,
        metadata: dict[str, str],
        ticket_id: str | None = None,
        action_id: str | None = None,
    ) -> None:
        event_id = (
            f"AUDIT-{uuid4()}"
        )

        event = AuditEvent(
            event_id=event_id,
            event_type=event_type,
            user_id=user_id,
            ticket_id=ticket_id,
            action_id=action_id,
            actor="self_healing_agent",
            description=description,
            metadata=metadata,
            created_at=datetime.now(
                timezone.utc
            ),
        )

        self._audit_repository.save(
            event
        )

        audit_event_ids.append(
            event_id
        )

